"""updated database for the multiple posts

Revision ID: 2c11a113ef6b
Revises: 7c2a91d4e6b0
Create Date: 2026-10-06 16:17:38.542596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c11a113ef6b'
down_revision: Union[str, Sequence[str], None] = '7c2a91d4e6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
